services:
  ansible:
    build: .
    entrypoint: ansible-playbook
    command: /pretendo/support/ansible/playbook.yml
    networks:
      internal:
    dns: 172.20.0.200
    volumes:
      - type: bind
        source: ../../
        target: /pretendo
        read_only: true
    environment:
      - MACHINE_IP=${MACHINE_IP?}
      - POSTGRES_USER=postgres_pretendo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?}
      - MINIO_URL=http://minio.pretendo.cc
      - MINIO_USER=minio_pretendo
      - MINIO_PASSWORD=${MINIO_ROOT_PASSWORD?}
      - PN_FRIENDS_CONFIG_PID_HMAC_KEY=${PN_FRIENDS_CONFIG_PID_HMAC_KEY?}
      - PN_MIIVERSE_API_CONFIG_AES_KEY=${PN_MIIVERSE_API_CONFIG_AES_KEY?}
