- name: MongoDB setup
  hosts: localhost
  tasks:
  - name: Ensure replicaset rs exists
    community.mongodb.mongodb_replicaset:
      login_host: mongodb
      replica_set: rs
      validate: false
      members: mongodb:27017
  - name: Wait for the replicaset to stabilise
    community.mongodb.mongodb_status:
      login_host: mongodb
      replica_set: rs
      poll: 1
      interval: 2

- name: PostgreSQL setup
  hosts: localhost
  vars:
    postgres_user: "{{ lookup('ansible.builtin.env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('ansible.builtin.env', 'POSTGRES_PASSWORD') }}"
  tasks:
    - name: Create DB for SMM
      community.postgresql.postgresql_db:
        name: "super_mario_maker"
        owner: "{{ postgres_user }}"
        login_host: "postgres"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        state: present

- name: MinIO setup
  hosts: localhost
  vars:
    postgres_user: "{{ lookup('ansible.builtin.env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('ansible.builtin.env', 'POSTGRES_PASSWORD') }}"
  tasks:
    - name: Create DB for SMM
      community.postgresql.postgresql_db:
        name: "super_mario_maker"
        owner: "{{ postgres_user }}"
        login_host: "postgres"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        state: present