networks:
  default: # We need to use a custom network so that we can set a static IP address for

  # CoreDNS and use it as a DNS server for the other containers.
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
