TOOL='docker-compose'
OUT_FILE='compose.yml'

echo "# This file is autogenerated by up.sh, do not edit it." > $OUT_FILE

# Begin writing compose file

echo "name: pretendo-network" >> $OUT_FILE
echo "include:" >> $OUT_FILE
echo "  - support/compose.base.yml" >> $OUT_FILE

for file in ./{services,support,servers,games}/*/compose.yml; do
    echo "  - $file" >> $OUT_FILE
done

$TOOL -f $OUT_FILE up $*
