services:
  pikmin-3:
    build: .
    depends_on:
      - account
      - postgres
    restart: unless-stopped
    ports:
      # Authentication server
      - 6010:6010/udp
      # Secure server
      - 6011:6011/udp
    networks:
      internal:
    dns: 172.20.0.200
    environment:
      - PN_PIKMIN3_AUTHENTICATION_SERVER_PORT=6010
      - PN_PIKMIN3_SECURE_SERVER_PORT=6011
      - PN_PIKMIN3_ACCOUNT_GRPC_HOST=account
      - PN_PIKMIN3_ACCOUNT_GRPC_PORT=5000
      - PN_PIKMIN3_ACCOUNT_GRPC_API_KEY=${PN_ACT_CONFIG_GRPC_MASTER_API_KEY_API?}
      - PN_PIKMIN3_POSTGRES_URI=postgres://postgres_pretendo:${POSTGRES_PASSWORD?}@postgres/pikmin3?sslmode=disable
      - PN_PIKMIN3_KERBEROS_PASSWORD=${PN_PIKMIN3_KERBEROS_PASSWORD?}
      - PN_PIKMIN3_SECURE_SERVER_HOST=${PN_PIKMIN3_SECURE_SERVER_HOST?}
