services:
  account:
    image: ghcr.io/pretendonetwork/account
    depends_on:
      - coredns-internal
      - nginx
      - mongodb
      - minio
      - redis
      - mailpit
    restart: always
    networks:
      internal:
    dns: 172.20.0.200
    environment:
      - PN_ACT_CONFIG_S3_BUCKET=account
      - PN_ACT_CONFIG_S3_ENDPOINT=http://minio.pretendo.cc
      - PN_ACT_CONFIG_S3_ACCESS_KEY=minio_pretendo
      - PN_ACT_CONFIG_S3_ACCESS_SECRET=${MINIO_ROOT_PASSWORD?}
      - PN_ACT_CONFIG_S3_REGION=us-east-1
      - PN_ACT_CONFIG_HTTP_PORT=8080
      - PN_ACT_CONFIG_MONGO_CONNECTION_STRING=mongodb://mongodb:27017/pretendo_account?replicaSet=rs
      - PN_ACT_CONFIG_CDN_BASE_URL=http://cdn.pretendo.cc
      - PN_ACT_CONFIG_AES_KEY=${PN_ACT_CONFIG_AES_KEY?}
      - PN_ACT_CONFIG_GRPC_PORT=5000
      - PN_ACT_CONFIG_GRPC_MASTER_API_KEY_ACCOUNT=${PN_ACT_CONFIG_GRPC_MASTER_API_KEY_ACCOUNT?}
      - PN_ACT_CONFIG_GRPC_MASTER_API_KEY_API=${PN_ACT_CONFIG_GRPC_MASTER_API_KEY_API?}
      - PN_ACT_CONFIG_REDIS_URL=redis://redis:6379
