services:
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    depends_on:
      - coredns-internal
      - redis
    restart: always
    ports:
      # Web interface
      - 127.0.0.1:8086:8086
    networks:
      internal:
    dns: 172.20.0.200
    environment:
      - PORT=8086
      - REDIS_HOST=redis
      - REDIS_PORT=6379
