- name: MongoDB setup
  hosts: localhost
  vars:
    mongo_pretendo_account: mongodb://mongodb:27017/pretendo_account?replicaSet=rs
    mongo_pretendo_miiverse: mongodb://mongodb:27017/pretendo_miiverse?replicaSet=rs
    machine_ip: "{{ lookup('ansible.builtin.env', 'MACHINE_IP') }}"
    friends_aes_key: "{{ lookup('ansible.builtin.env', 'PN_FRIENDS_CONFIG_PID_HMAC_KEY') }}"
    miiverse_aes_key: "{{ lookup('ansible.builtin.env', 'PN_MIIVERSE_API_CONFIG_AES_KEY') }}"
  tasks:
    - name: Ensure replicaset rs exists
      community.mongodb.mongodb_replicaset:
        login_host: mongodb
        replica_set: rs
        validate: false
        members: mongodb:27017
    - name: Wait for the replicaset to stabilise
      community.mongodb.mongodb_status:
        login_host: mongodb
        replica_set: rs
        poll: 1
        interval: 2
    - name: NEX Server for Friends List
      create_nex_server:
        mongo_connection_string: "{{ mongo_pretendo_account }}"
        service_name: Friend List
        game_server_id: "00003200"
        title_ids:
          # Not in the title database but seems to be what the Wii U sends
          - "0005001010001C00"
          # Wii U Friend List
          - "000500301001500A"
          - "000500301001510A"
          - "000500301001520A"
          # 3DS friends system-module
          - "0004013000003202"
          # 3DS Friend List applet
          - "0004003000008D02"
          - "0004003000009602"
          - "0004003000009F02"
          - "000400300000AF02"
        ip: "{{ machine_ip }}"
        port: 6000
        device: 1
        aes_key: "{{ friends_aes_key }}"
        access_levels:
          - prod
          - test
          - dev
        state: present
    - name: Service for Miiverse
      create_service:
        mongo_connection_string: "{{ mongo_pretendo_account }}"
        service_name: Miiverse
        client_id: "87cd32617f1985439ea608c2746e4610"
        title_ids:
          # Wii U Miiverse
          - "000500301001600A"
          - "000500301001610A"
          - "000500301001620A"
          # 3DS Miiverse applet
          - "000400300000BC02"
          - "000400300000BD02"
          - "000400300000BE02"
        device: 1
        aes_key: "{{ miiverse_aes_key }}"
        access_levels:
          - prod
          - test
          - dev
        state: present
    - name: Endpoints for Miiverse
      create_miiverse_endpoint:
        mongo_connection_string: "{{ mongo_pretendo_miiverse }}"
        status: 0
        host: "api.olv.pretendo.cc"
        api_host: "api.olv.pretendo.cc"
        portal_host: "portal.olv.pretendo.cc"
        n3ds_host: "ctr.olv.pretendo.cc"
        access_levels:
          - prod
          - test
          - dev
        state: present
