- name: PostgreSQL setup
  hosts: localhost
  vars:
    postgres_user: "{{ lookup('ansible.builtin.env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('ansible.builtin.env', 'POSTGRES_PASSWORD') }}"
  tasks:
    - name: Create DB for Friends
      community.postgresql.postgresql_db:
        name: "friends"
        owner: "{{ postgres_user }}"
        login_host: "postgres"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        state: present
    - name: Create DB for Miiverse
      community.postgresql.postgresql_db:
        name: "miiverse"
        owner: "{{ postgres_user }}"
        login_host: "postgres"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        state: present
    - name: Create DB for SMM
      community.postgresql.postgresql_db:
        name: "super_mario_maker"
        owner: "{{ postgres_user }}"
        login_host: "postgres"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        state: present
