services:
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - coredns-internal
      - mongodb
    restart: always
    ports:
      # Web interface
      - 127.0.0.1:8082:8082
    networks:
      internal:
    dns: 172.20.0.200
    environment:
      - PORT=8082
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
