services:
  boss:
    build: .
    depends_on:
      - account
      - mongodb
    restart: always
    ports:
      # Node.js debugger
      - 127.0.0.1:9233:9233
    volumes:
      - type: bind
        source: ./config/mongoose-connect-options.json
        target: /home/node/app/mongoose-connect-options.json
        read_only: true
    networks:
      internal:
    dns: 172.20.0.200
    command: ["node", "--inspect=0.0.0.0:9233", "."]
    environment:
      - PN_BOSS_CONFIG_HTTP_PORT=8080
      - PN_BOSS_CONFIG_MONGOOSE_CONNECT_OPTIONS_PATH=/home/node/app/mongoose-connect-options.json
      - PN_BOSS_CONFIG_GRPC_BOSS_SERVER_ADDRESS=0.0.0.0
      - PN_BOSS_CONFIG_GRPC_BOSS_SERVER_PORT=5002
      - PN_BOSS_CONFIG_GRPC_BOSS_SERVER_API_KEY=${PN_BOSS_CONFIG_GRPC_BOSS_SERVER_API_KEY?}
      - PN_BOSS_CONFIG_GRPC_ACCOUNT_SERVER_ADDRESS=account
      - PN_BOSS_CONFIG_GRPC_ACCOUNT_SERVER_PORT=5000
      - PN_BOSS_CONFIG_GRPC_ACCOUNT_SERVER_API_KEY=EM2zaZtrsrl25uTjtQ5eThLAN7YxCVWy
      - PN_BOSS_CONFIG_GRPC_FRIENDS_SERVER_ADDRESS=friends
      - PN_BOSS_CONFIG_GRPC_FRIENDS_SERVER_PORT=5001
      - PN_BOSS_CONFIG_GRPC_FRIENDS_SERVER_API_KEY=${PN_BOSS_CONFIG_GRPC_FRIENDS_SERVER_API_KEY?}
      - PN_BOSS_CONFIG_MONGO_CONNECTION_STRING=mongodb://mongodb:27017/pretendo_boss?replicaSet=rs
      - PN_BOSS_CONFIG_CDN_DOWNLOAD_URL=https://npdi.cdn.pretendo.cc
      - PN_BOSS_CONFIG_S3_ENDPOINT=http://minio.pretendo.cc
      - PN_BOSS_CONFIG_S3_REGION=us-east-1
      - PN_BOSS_CONFIG_S3_BUCKET=pn-boss
      - PN_BOSS_CONFIG_S3_ACCESS_KEY=minio_pretendo
      - PN_BOSS_CONFIG_S3_ACCESS_SECRET=${PN_BOSS_CONFIG_S3_ACCESS_SECRET?}
      - PN_BOSS_CONFIG_BOSS_3DS_AES_KEY=${PN_BOSS_CONFIG_BOSS_3DS_AES_KEY?}
