volumes:
  redis-data:

services:
  redis:
    image: redis:alpine
    depends_on:
      - coredns-internal
    restart: always
    volumes:
      - type: volume
        source: redis-data
        target: /data
    networks:
      internal:
    dns: 172.20.0.200
    command: redis-server --save 60 1