services:
  friends:
    build: .
    depends_on:
      - account
      - postgres
    restart: always
    ports:
      # Go delve debugger
      - 127.0.0.1:2345:2345
      # Authentication server
      - 6000:6000/udp
      # Secure server
      - 6001:6001/udp
    networks:
      internal:
    dns: 172.20.0.200
    environment:
      - PN_FRIENDS_ACCOUNT_GRPC_HOST=account
      - PN_FRIENDS_ACCOUNT_GRPC_PORT=5000
      - PN_FRIENDS_GRPC_SERVER_PORT=5001
      - PN_FRIENDS_AUTHENTICATION_SERVER_PORT=6000
      - PN_FRIENDS_SECURE_SERVER_PORT=6001
      - PN_FRIENDS_ACCOUNT_GRPC_API_KEY=${PN_ACT_CONFIG_GRPC_MASTER_API_KEY_API?}
      - PN_FRIENDS_CONFIG_POSTGRES_URI=postgres://postgres_pretendo:${POSTGRES_PASSWORD?}@postgres/friends?sslmode=disable
      - PN_FRIENDS_CONFIG_AUTHENTICATION_PASSWORD=${PN_FRIENDS_CONFIG_AUTHENTICATION_PASSWORD?}
      - PN_FRIENDS_CONFIG_SECURE_PASSWORD=${PN_FRIENDS_CONFIG_SECURE_PASSWORD?}
      - PN_FRIENDS_CONFIG_GRPC_API_KEY=${PN_FRIENDS_CONFIG_GRPC_API_KEY?}
      - PN_FRIENDS_CONFIG_AES_KEY=${PN_FRIENDS_CONFIG_AES_KEY?}
      - PN_FRIENDS_SECURE_SERVER_HOST=${PN_FRIENDS_SECURE_SERVER_HOST?}
