volumes:
  mailpit-mail:

services:
  mailpit:
    image: axllent/mailpit:latest
    depends_on:
      - coredns-internal
    restart: always
    ports:
      # Mailpit web UI
      - 127.0.0.1:8084:8084
    volumes:
      - type: volume
        source: mailpit-mail
        target: /data
    networks:
      internal:
    dns: 172.20.0.200
    environment:
      - MP_SMTP_BIND_ADDR=0.0.0.0:1025
      - MP_UI_BIND_ADDR=0.0.0.0:8084
      - MP_DATABASE=/data/mailpit.db
